# Generated by Django 6.0.7 on 2026-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, upload_to='passports/', verbose_name='passport'),
        ),
    ]
