# Generated by Django 6.0.7 on 2026-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_plan_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='local_government_area',
            field=models.CharField(blank=True, max_length=100, verbose_name='local government area (L.G.A.)'),
        ),
        migrations.AddField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='state of origin'),
        ),
        migrations.AddField(
            model_name='studentguardianlink',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='guardian address'),
        ),
        migrations.AddField(
            model_name='studentguardianlink',
            name='authorized_pickup_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='authorized person for after-school pick-up'),
        ),
        migrations.AddField(
            model_name='studentguardianlink',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='guardian occupation'),
        ),
    ]
