# Generated by Django 6.0.7 on 2026-09-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_test_max_scores'),
        ('students', '0005_add_state_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_paid_term',
            field=models.ForeignKey(blank=True, help_text='The term in which the student paid the one-time Registration Form fee. Once set, the student is treated as RETURNING for subsequent terms even if their first ClassEnrollment is in the current session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_paid_students', to='core.term', verbose_name='registration paid term'),
        ),
    ]
