# Generated by Django 6.0.7 on 2026-09-02 15:16

from django.db import migrations, models


def backfill_student_type(apps, schema_editor):
    """Backfill student_type based on prior ClassEnrollments.

    A student is RETURNING if they have a ClassEnrollment whose session
    started before the current session. Otherwise they stay NEW.
    """
    Student = apps.get_model('students', 'Student')
    ClassEnrollment = apps.get_model('students', 'ClassEnrollment')
    AcademicSession = apps.get_model('core', 'AcademicSession')

    current_session = AcademicSession.objects.filter(is_current=True).first()
    if not current_session:
        return

    for student in Student.objects.all():
        has_prior = ClassEnrollment.objects.filter(
            student=student,
            session__start_date__lt=current_session.start_date,
        ).exists()
        if has_prior:
            student.student_type = 'RETURNING'
            student.save(update_fields=['student_type'])


def rollback_student_type(apps, schema_editor):
    """Reverse: reset all to NEW."""
    Student = apps.get_model('students', 'Student')
    Student.objects.update(student_type='NEW')


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_registration_paid_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('NEW', 'New'), ('RETURNING', 'Returning')], default='NEW', help_text='NEW = first year onboarding applies (Registration, Uniforms, PTA, etc.). Auto-flips to RETURNING after the Registration Form fee is paid.', max_length=20, verbose_name='student type'),
        ),
        migrations.RunPython(backfill_student_type, rollback_student_type),
    ]
