# Generated by Django 6.0.7 on 2026-08-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_session_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='account name'),
        ),
        migrations.AddField(
            model_name='school',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='account number'),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='bank name'),
        ),
    ]
