# Generated by Django 6.0.7 on 2026-08-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_school_account_name_school_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='exam_max_score',
            field=models.PositiveSmallIntegerField(default=70, help_text='Maximum marks for the examination component', verbose_name='exam max score'),
        ),
        migrations.AddField(
            model_name='school',
            name='test_max_score',
            field=models.PositiveSmallIntegerField(default=10, help_text='Maximum marks for each continuous assessment test (Test 1, 2, 3)', verbose_name='test max score'),
        ),
    ]
