# Generated by Django 6.0.7 on 2026-08-19 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_school_exam_max_score_school_test_max_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=50, verbose_name='model')),
                ('object_id', models.CharField(db_index=True, max_length=50, verbose_name='object id')),
                ('action', models.CharField(choices=[('CREATE', 'created'), ('UPDATE', 'updated'), ('DELETE', 'deleted')], max_length=10, verbose_name='action')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='summary')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
