# Generated by Django 6.0.7 on 2026-08-26 18:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='test_max_score',
        ),
        migrations.AddField(
            model_name='school',
            name='test_max_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Maximum marks per test, e.g. {"test_1": 10, "test_2": 10, "test_3": 10}', verbose_name='test max scores'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='changes'),
        ),
    ]
