# Generated by Django 6.0.7 on 2026-09-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_fix_test_max_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id_int',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='object id (int)'),
        ),
    ]
