# Generated by Django 6.0.7 on 2026-07-14 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'expenditure category',
                'verbose_name_plural': 'expenditure categories',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='target amount')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=20, verbose_name='status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('target_end_date', models.DateField(blank=True, null=True, verbose_name='target end date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('date', models.DateField(verbose_name='date')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expenditures', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='finance.expenditurecategory', verbose_name='category')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='finance.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'expenditure',
                'verbose_name_plural': 'expenditures',
                'ordering': ['-date'],
            },
        ),
    ]
