# Generated by Django 6.0.7 on 2026-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_flexible_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='is_compulsory',
            field=models.BooleanField(default=True, help_text='Compulsory categories (e.g. school fees) are billed automatically on every term invoice. Optional categories (e.g. uniform) only appear as payable extras a parent chooses to pay.', verbose_name='compulsory'),
        ),
    ]
