# Generated by Django 6.0.7 on 2026-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_feecategory_is_compulsory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_by_relation',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='paid by relation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.FileField(blank=True, help_text='Screenshot or receipt image proving a bank transfer.', null=True, upload_to='fees/proofs/%Y/%m/', verbose_name='transfer proof'),
        ),
    ]
