# Generated by Django 6.0.7 on 2026-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_payment_paid_by_relation_payment_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('POS', 'POS / Card at school'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('USSD', 'USSD'), ('PAYSTACK', 'Paystack'), ('OTHER', 'Other')], max_length=20, verbose_name='method'),
        ),
    ]
