# Generated by Django 6.0.7 on 2026-08-19 06:59

import django.db.models.deletion
import fees.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmed at'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='confirmed by'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=models.FileField(blank=True, help_text='Screenshot or receipt image proving a bank transfer.', null=True, upload_to='fees/proofs/%Y/%m/', validators=[fees.validators.validate_proof_file], verbose_name='transfer proof'),
        ),
    ]
