# Generated by Django 6.0.7 on 2026-08-20 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_payment_confirmed_at_payment_confirmed_by_and_more'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lesson_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='lessons.lessonenrollment', verbose_name='lesson enrollment'),
        ),
    ]
