# Generated by Django 6.0.7 on 2026-09-01 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_test_max_scores'),
        ('fees', '0008_payment_lesson_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('outstanding', 'Outstanding'), ('extra', 'Extra'), ('next', 'Next term')], max_length=20, verbose_name='kind')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('source_key', models.CharField(max_length=100, verbose_name='source key')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feecategory', verbose_name='category')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.invoice', verbose_name='invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='fees.payment', verbose_name='payment')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicsession', verbose_name='session')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'payment line item',
                'verbose_name_plural': 'payment line items',
                'ordering': ['id'],
            },
        ),
    ]
