# Generated by Django 6.0.7 on 2026-09-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_test_max_scores'),
        ('fees', '0009_payment_line_item'),
        ('students', '0005_add_state_of_origin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='billing_cycle',
            field=models.CharField(choices=[('ONE_TIME', 'One-time'), ('PER_TERM', 'Per term')], default='PER_TERM', help_text='One-time fees apply only once (e.g. registration). Per-term fees recur each term.', max_length=20, verbose_name='billing cycle'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='student_type',
            field=models.CharField(choices=[('NEW', 'New intake only'), ('RETURNING', 'Returning pupils only'), ('ALL', 'All students')], default='ALL', help_text='Which students this category applies to.', max_length=20, verbose_name='student type'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='student_type',
            field=models.CharField(choices=[('NEW', 'New intake only'), ('RETURNING', 'Returning pupils only'), ('ALL', 'All students')], default='ALL', help_text='Which students this price applies to.', max_length=20, verbose_name='student type'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Leave blank for one-time fees.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term', verbose_name='term'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'school_class', 'term', 'category', 'student_type')},
        ),
    ]
