# Generated by Django 6.0.7 on 2026-09-01 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_test_max_scores'),
        ('fees', '0010_alter_feestructure_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'ordering': ['id'], 'verbose_name': 'invoice line item', 'verbose_name_plural': 'invoice line items'},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_recurring_override',
            field=models.BooleanField(blank=True, help_text='Override billing_cycle for this specific class/term. None = use category default.', null=True, verbose_name='recurring override'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='billing_cycle',
            field=models.CharField(choices=[('ONE_TIME', 'One-time'), ('PER_TERM', 'Per term')], default='PER_TERM', max_length=20, verbose_name='billing cycle'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicsession', verbose_name='session'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term', verbose_name='term'),
        ),
        migrations.AddField(
            model_name='paymentlineitem',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school'),
        ),
        migrations.CreateModel(
            name='FeeCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('group_type', models.CharField(choices=[('RECURRING', 'Recurring (per-term)'), ('ONE_OFF', 'One-off')], default='RECURRING', max_length=20, verbose_name='group type')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fees.feecategorygroup', verbose_name='parent group')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'fee category group',
                'verbose_name_plural': 'fee category groups',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='feecategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='fees.feecategorygroup', verbose_name='group'),
        ),
        migrations.CreateModel(
            name='FeeValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('NEGATIVE_AMOUNT', 'Negative amount'), ('DUPLICATE_STRUCTURE', 'Duplicate fee structure'), ('MISMATCHED_TOTAL', 'Invoice total != sum of line items'), ('MISSING_COMPULSORY', 'Missing compulsory category'), ('ONE_TIME_REBILL', 'One-time fee rebilled to same student'), ('INVALID_STUDENT_TYPE', 'Invalid student type for category')], max_length=50, verbose_name='code')),
                ('message', models.TextField(verbose_name='message')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='related object type')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='related object id')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'fee validation error',
                'verbose_name_plural': 'fee validation errors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('TERM', 'Term'), ('CLASS', 'Class'), ('STUDENT', 'Student'), ('SCHOOL', 'School-wide')], max_length=20, verbose_name='scope type')),
                ('scope_id', models.PositiveIntegerField(verbose_name='scope id')),
                ('scope_name', models.CharField(max_length=200, verbose_name='scope name')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('invoices_deleted', models.PositiveIntegerField(default=0, verbose_name='invoices deleted')),
                ('payments_deleted', models.PositiveIntegerField(default=0, verbose_name='payments deleted')),
                ('line_items_deleted', models.PositiveIntegerField(default=0, verbose_name='line items deleted')),
                ('receipts_deleted', models.PositiveIntegerField(default=0, verbose_name='receipts deleted')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='performed at')),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='reset by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'invoice reset log',
                'verbose_name_plural': 'invoice reset logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategoryGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='fees.feecategory', verbose_name='category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fees.feecategorygroup', verbose_name='group')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'fee category group assignment',
                'verbose_name_plural': 'fee category group assignments',
                'ordering': ['sort_order', 'category__name'],
                'unique_together': {('school', 'group', 'category')},
            },
        ),
    ]
