# Generated by Django 6.0.7 on 2026-09-01 12:33

from django.db import migrations


def backfill_invoice_line_item_school(apps, schema_editor):
    InvoiceLineItem = apps.get_model('fees', 'InvoiceLineItem')
    updated = 0
    for item in InvoiceLineItem.objects.filter(school__isnull=True).select_related('invoice__school', 'invoice__term__session'):
        item.school = item.invoice.school
        item.term = item.invoice.term
        item.session = item.invoice.term.session if item.invoice.term else None
        item.save(update_fields=['school', 'term', 'session'])
        updated += 1
    print(f'Backfilled {updated} InvoiceLineItem rows with school/term/session.')


def backfill_payment_line_item_school(apps, schema_editor):
    PaymentLineItem = apps.get_model('fees', 'PaymentLineItem')
    updated = 0
    for item in PaymentLineItem.objects.filter(school__isnull=True).select_related('payment__school'):
        item.school = item.payment.school
        item.save(update_fields=['school'])
        updated += 1
    print(f'Backfilled {updated} PaymentLineItem rows with school.')


def create_default_groups(apps, schema_editor):
    FeeCategoryGroup = apps.get_model('fees', 'FeeCategoryGroup')
    School = apps.get_model('core', 'School')
    for school in School.objects.all():
        FeeCategoryGroup.objects.get_or_create(
            school=school,
            name='Academic',
            defaults={'group_type': 'RECURRING', 'sort_order': 0},
        )
        FeeCategoryGroup.objects.get_or_create(
            school=school,
            name='Auxiliary',
            defaults={'group_type': 'RECURRING', 'sort_order': 1},
        )
        FeeCategoryGroup.objects.get_or_create(
            school=school,
            name='One-off',
            defaults={'group_type': 'ONE_OFF', 'sort_order': 2},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_add_payment_reset_models'),
    ]

    operations = [
        migrations.RunPython(backfill_invoice_line_item_school, migrations.RunPython.noop),
        migrations.RunPython(backfill_payment_line_item_school, migrations.RunPython.noop),
        migrations.RunPython(create_default_groups, migrations.RunPython.noop),
    ]
