# Generated by Django 6.0.7 on 2026-09-02 08:55

import django.db.models.deletion
from django.db import migrations, models


def copy_feestructures_to_feeprices(apps, schema_editor):
    FeeStructure = apps.get_model('fees', 'FeeStructure')
    FeePrice = apps.get_model('fees', 'FeePrice')
    
    batch = []
    for fs in FeeStructure.objects.all():
        batch.append(FeePrice(
            school=fs.school,
            category=fs.category,
            amount=fs.amount,
            term=fs.term,
            student_type=fs.student_type,
            scope=fs.scope,
            school_class=fs.school_class,
            level='',
            is_active=True,
            effective_from=None,
            effective_to=None,
        ))
        fs.deprecated = True
        fs.save(update_fields=['deprecated'])
    
    if batch:
        FeePrice.objects.bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_test_max_scores'),
        ('fees', '0012_add_fee_structure_scope'),
        ('students', '0005_add_state_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='deprecated',
            field=models.BooleanField(default=False, help_text='Migrated to FeePrice. Kept for backward compatibility.', verbose_name='deprecated'),
        ),
        migrations.CreateModel(
            name='FeePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('student_type', models.CharField(choices=[('NEW', 'New intake only'), ('RETURNING', 'Returning pupils only'), ('ALL', 'All students')], default='ALL', help_text='Which students this price applies to.', max_length=20, verbose_name='student type')),
                ('scope', models.CharField(choices=[('SCHOOL_WIDE', 'School-wide'), ('LEVEL', 'Level/Grade'), ('CLASS', 'Class-specific')], default='CLASS', max_length=20, verbose_name='scope')),
                ('level', models.CharField(blank=True, help_text='Level code for LEVEL-scoped prices, e.g. JSS, PRIMARY.', max_length=100, verbose_name='level')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive prices are ignored during resolution.', verbose_name='active')),
                ('effective_from', models.DateField(blank=True, help_text='Leave blank to apply immediately.', null=True, verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank for no expiry.', null=True, verbose_name='effective to')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feecategory', verbose_name='category')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass', verbose_name='school class')),
                ('term', models.ForeignKey(blank=True, help_text='Leave blank for one-time fees.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'fee price',
                'verbose_name_plural': 'fee prices',
                'ordering': ['scope', 'school_class', 'level', 'category'],
                'unique_together': {('school', 'scope', 'school_class', 'level', 'term', 'category', 'student_type')},
            },
        ),
        migrations.RunPython(copy_feestructures_to_feeprices, migrations.RunPython.noop),
    ]
