# Generated by Django 6.0.7 on 2026-09-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_test_max_scores'),
        ('fees', '0013_feestructure_deprecated_feeprice'),
        ('students', '0005_add_state_of_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('reason', models.CharField(blank=True, help_text='Optional reason for the override.', max_length=255, verbose_name='reason')),
                ('valid_from', models.DateField(help_text='Override applies from this date.', verbose_name='valid from')),
                ('valid_to', models.DateField(help_text='Override applies until this date. Leave far future for permanent.', verbose_name='valid to')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive overrides are ignored.', verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feecategory', verbose_name='category')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_price_overrides', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'fee price override',
                'verbose_name_plural': 'fee price overrides',
                'ordering': ['-valid_from', 'category__name'],
                'unique_together': {('school', 'student', 'category', 'valid_from', 'valid_to')},
            },
        ),
    ]
