# Generated by Django 6.0.7 on 2026-09-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_feepriceoverride'),
    ]

    operations = [
    ]
