# Generated by Django 6.0.7 on 2026-09-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_test_max_scores'),
        ('fees', '0015_drop_feestructure_legacy'),
        ('students', '0005_add_state_of_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['school_class', 'category'], 'verbose_name': 'fee structure (legacy)', 'verbose_name_plural': 'fee structures (legacy)'},
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feecategory'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='deprecated',
            field=models.BooleanField(default=True, help_text='Always true: this model is the legacy compatibility shim for FeePrice.'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='is_recurring_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='scope',
            field=models.CharField(choices=[('CLASS', 'Class-specific'), ('SCHOOL_WIDE', 'School-wide (all classes)')], default='CLASS', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='student_type',
            field=models.CharField(choices=[('NEW', 'New intake only'), ('RETURNING', 'Returning pupils only'), ('ALL', 'All students')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
    ]
