# Generated by Django 6.0.7 on 2026-09-02 13:36

from django.db import migrations


def remove_duplicate_one_time_prices(apps, schema_editor):
    """Remove per-class duplicate ONE_TIME prices.

    After Phase 2 migration, school-wide ONE_TIME prices were created for
    categories like PTA, Registration Form, Uniforms, etc. Old per-class
    duplicates from earlier seed runs were left in place, causing
    FeePrice resolution to return many rows for the same category.

    For each ONE_TIME category, keep at most one school-wide row and
    delete all per-class duplicates.
    """
    FeePrice = apps.get_model('fees', 'FeePrice')
    FeeCategory = apps.get_model('fees', 'FeeCategory')

    for cat in FeeCategory.objects.filter(billing_cycle='ONE_TIME'):
        class_rows = FeePrice.objects.filter(
            category=cat,
            scope='CLASS',
            school_class__isnull=False,
        )
        if class_rows.exists():
            school_wide = FeePrice.objects.filter(
                category=cat,
                scope='SCHOOL_WIDE',
                school_class__isnull=True,
                level='',
            ).first()
            if not school_wide:
                first = class_rows.first()
                FeePrice.objects.create(
                    school=first.school,
                    scope='SCHOOL_WIDE',
                    school_class=None,
                    level='',
                    term=first.term,
                    category=cat,
                    student_type=first.student_type,
                    amount=first.amount,
                    is_active=first.is_active,
                )
            class_rows.delete()


def remove_old_term_prices(apps, schema_editor):
    """Remove FeePrice rows that don't belong to the current term."""
    FeePrice = apps.get_model('fees', 'FeePrice')
    School = apps.get_model('core', 'School')
    Term = apps.get_model('core', 'Term')

    for school in School.objects.all():
        current_term = Term.objects.filter(school=school, is_current=True).first()
        if not current_term:
            continue
        FeePrice.objects.filter(school=school).exclude(term=current_term).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0016_alter_feestructure_options_alter_feestructure_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_one_time_prices, migrations.RunPython.noop),
        migrations.RunPython(remove_old_term_prices, migrations.RunPython.noop),
    ]
