# Generated by Django 6.0.7 on 2026-09-02 15:08

from django.db import migrations


def remove_school_fees_categories(apps, schema_editor):
    """Delete 'X School Fees' categories (e.g. JSS1 School Fees).

    The X School Fees categories are duplicates of the per-class Tuition Fee
    (both are per-term, both are class-scoped, both have the same amount).
    After this migration, the canonical per-term class fee is Tuition Fee.
    All orphan FeePrice and FeeStructure (legacy) rows are removed too.
    """
    FeeCategory = apps.get_model('fees', 'FeeCategory')
    FeePrice = apps.get_model('fees', 'FeePrice')
    FeeStructure = apps.get_model('fees', 'FeeStructure')

    school_fees_cats = FeeCategory.objects.filter(name__regex=r'School Fees$')

    FeePrice.objects.filter(category__in=school_fees_cats).delete()
    FeeStructure.objects.filter(category__in=school_fees_cats).delete()
    school_fees_cats.delete()


def restore_school_fees_categories(apps, schema_editor):
    """No-op reverse: this is a destructive data migration.

    Categories and prices would have to be re-seeded via the
    seed_fee_structure command.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0017_cleanup_duplicate_one_time_prices'),
    ]

    operations = [
        migrations.RunPython(remove_school_fees_categories, restore_school_fees_categories),
    ]
