# Generated by Django 6.0.7 on 2026-09-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0018_delete_school_fees_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verify_attempted',
            field=models.BooleanField(default=False, verbose_name='verify attempted'),
        ),
    ]
