# Generated by Django 6.0.7 on 2026-09-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditlog_content_type_auditlog_object_id_int'),
        ('fees', '0019_payment_verify_attempted'),
        ('students', '0007_student_student_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecategory',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='school',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='term',
        ),
        migrations.AlterUniqueTogether(
            name='feepriceoverride',
            unique_together={('school', 'student', 'category')},
        ),
        migrations.DeleteModel(
            name='FeeCategoryGroup',
        ),
        migrations.DeleteModel(
            name='FeeCategoryGroupAssignment',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
    ]
