# Generated by Django 6.0.7 on 2026-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0020_remove_feecategory_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeprice',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Display name for this item, e.g. "Tuition Fee — JSS1A". Leave blank to use the category name.', max_length=200, verbose_name='item name'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='item_name',
            field=models.CharField(blank=True, default='', help_text='Denormalized display name captured at generation time so old invoices keep their original wording.', max_length=200, verbose_name='item name'),
        ),
    ]
