# Generated by Django 6.0.7 on 2026-09-16 13:38

from django.db import migrations


def backfill_fee_price_names(apps, schema_editor):
    FeePrice = apps.get_model('fees', 'FeePrice')
    updated = 0
    for price in FeePrice.objects.filter(name='').select_related('category'):
        price.name = price.category.name
        price.save(update_fields=['name'])
        updated += 1
    print(f'Backfilled {updated} FeePrice rows with category name.')


def backfill_invoice_line_item_names(apps, schema_editor):
    InvoiceLineItem = apps.get_model('fees', 'InvoiceLineItem')
    updated = 0
    for item in InvoiceLineItem.objects.filter(item_name='').select_related('category'):
        item.item_name = item.category.name
        item.save(update_fields=['item_name'])
        updated += 1
    print(f'Backfilled {updated} InvoiceLineItem rows with category name.')


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0021_feeprice_name_invoicelineitem_item_name'),
    ]

    operations = [
        migrations.RunPython(backfill_fee_price_names, migrations.RunPython.noop),
        migrations.RunPython(backfill_invoice_line_item_names, migrations.RunPython.noop),
    ]