# Generated by Django 6.0.7 on 2026-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_alter_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.ImageField(blank=True, upload_to='passports/', verbose_name='passport'),
        ),
    ]
