# Generated by Django 6.0.7 on 2026-08-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set for accounts whose password was generated for them (bulk credential runs, resets, new student/parent creation). The user is forced to pick their own password on first login.', verbose_name='must change password'),
        ),
    ]
