# Generated by Django 6.0.7 on 2026-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_phones',
            field=models.JSONField(blank=True, default=list, help_text='Additional contact numbers as a JSON list of strings.', verbose_name='other phone numbers'),
        ),
    ]
