# Generated by Django 6.0.7 on 2026-07-15 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_term_results_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('classes', 'Classes'), ('subjects', 'Subjects'), ('students', 'Students'), ('staff', 'Staff')], max_length=20, verbose_name='import type')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='total rows')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='created count')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='skipped count')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='error count')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='errors')),
                ('dry_run', models.BooleanField(default=False, verbose_name='dry run')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='imported by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'import log',
                'verbose_name_plural': 'import logs',
                'ordering': ['-imported_at'],
            },
        ),
    ]
