# Generated by Django 6.0.7 on 2026-08-27 07:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_fix_test_max_scores'),
        ('fees', '0008_payment_lesson_enrollment'),
        ('students', '0004_plan_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('category', models.CharField(choices=[('BOOK', 'Book / Textbook'), ('NOTEBOOK', 'Notebook / Lesson Note'), ('WRITING', 'Pen / Pencil / Writing Material'), ('UNIFORM', 'Uniform / Wearable'), ('EQUIPMENT', 'Equipment / Device'), ('OTHER', 'Other')], default='BOOK', max_length=20, verbose_name='category')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('unit', models.CharField(default='piece', max_length=50, verbose_name='unit')),
                ('total_stock', models.PositiveIntegerField(default=0, verbose_name='total stock')),
                ('min_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='min stock threshold')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='unit price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('school_class', models.ForeignKey(help_text='Items without a class assignment are admin-only.', on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass', verbose_name='school class')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'ordering': ['category', 'name'],
                'unique_together': {('school', 'name', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='BookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchases', to='fees.payment', verbose_name='payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='student')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'book purchase',
                'verbose_name_plural': 'book purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryProcurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('procurement_date', models.DateField(verbose_name='procurement date')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='supplier')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit cost')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurements', to='inventory.inventoryitem', verbose_name='item')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='purchased by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'inventory procurement',
                'verbose_name_plural': 'inventory procurements',
                'ordering': ['-procurement_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PROCUREMENT', 'Procurement'), ('SALE', 'Sale'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20, verbose_name='type')),
                ('quantity_change', models.IntegerField(verbose_name='quantity change')),
                ('balance_after', models.PositiveIntegerField(verbose_name='balance after')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem', verbose_name='item')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'inventory transaction',
                'verbose_name_plural': 'inventory transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategoryInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='fees.feecategory', verbose_name='fee category')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='inventory.inventoryitem', verbose_name='inventory item')),
            ],
            options={
                'verbose_name': 'fee category inventory item',
                'verbose_name_plural': 'fee category inventory items',
                'unique_together': {('fee_category', 'inventory_item')},
            },
        ),
    ]
