# Generated by Django 6.0.7 on 2026-08-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('students', '0004_plan_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Leave blank for admin-only or teacher-use items.', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass', verbose_name='school class'),
        ),
    ]
