# Generated by Django 6.0.7 on 2026-07-13 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('role_filter', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], help_text='Optional: restrict this grade to a specific user role', max_length=20, null=True, verbose_name='role filter')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base salary')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'pay grade',
                'verbose_name_plural': 'pay grades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('pay_date', models.DateField(verbose_name='pay date')),
                ('generated_on', models.DateTimeField(auto_now_add=True, verbose_name='generated on')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'payroll run',
                'verbose_name_plural': 'payroll runs',
                'ordering': ['-generated_on'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base salary')),
                ('total_allowances', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total allowances')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total deductions')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='gross pay')),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='net pay')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun', verbose_name='payroll run')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'payslip',
                'verbose_name_plural': 'payslips',
            },
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('line_type', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction')], max_length=20, verbose_name='line type')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll.payslip', verbose_name='payslip')),
            ],
            options={
                'verbose_name': 'payslip line item',
                'verbose_name_plural': 'payslip line items',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, verbose_name='employee ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='bank name')),
                ('bank_account_number', models.CharField(max_length=50, verbose_name='bank account number')),
                ('bank_account_name', models.CharField(max_length=200, verbose_name='bank account name')),
                ('hire_date', models.DateField(verbose_name='hire date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('pay_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='payroll.paygrade', verbose_name='pay grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'staff profile',
                'verbose_name_plural': 'staff profiles',
                'unique_together': {('school', 'employee_id')},
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.staffprofile', verbose_name='staff'),
        ),
        migrations.CreateModel(
            name='DeductionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('pay_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_definitions', to='payroll.paygrade', verbose_name='pay grade')),
                ('target_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_definitions', to='payroll.staffprofile', verbose_name='target staff')),
            ],
            options={
                'verbose_name': 'deduction definition',
                'verbose_name_plural': 'deduction definitions',
            },
        ),
        migrations.CreateModel(
            name='AllowanceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('pay_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_definitions', to='payroll.paygrade', verbose_name='pay grade')),
                ('target_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_definitions', to='payroll.staffprofile', verbose_name='target staff')),
            ],
            options={
                'verbose_name': 'allowance definition',
                'verbose_name_plural': 'allowance definitions',
            },
        ),
        migrations.CreateModel(
            name='SalaryDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='method')),
                ('reference', models.CharField(max_length=255, verbose_name='reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('disbursed_on', models.DateTimeField(verbose_name='disbursed on')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='payroll.payslip', verbose_name='payslip')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'salary disbursement',
                'verbose_name_plural': 'salary disbursements',
                'ordering': ['-disbursed_on'],
                'unique_together': {('school', 'reference')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('school', 'staff', 'payroll_run')},
        ),
    ]
