# Generated by Django 6.0.7 on 2026-07-13 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('pass_mark', models.PositiveSmallIntegerField(default=40, verbose_name='pass mark')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='test 1')),
                ('test_2', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='test 2')),
                ('test_3', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='test 3')),
                ('exam_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='exam score')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='position')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='entered by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student', verbose_name='student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.term', verbose_name='term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
                'ordering': ['student__admission_number'],
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='students.schoolclass', verbose_name='class')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.academicsession', verbose_name='academic session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'teacher assignment',
                'verbose_name_plural': 'teacher assignments',
                'unique_together': {('teacher', 'subject', 'school_class', 'session')},
            },
        ),
    ]
