# Generated by Django 6.0.7 on 2026-07-14 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='moderated at'),
        ),
        migrations.AddField(
            model_name='score',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_scores', to=settings.AUTH_USER_MODEL, verbose_name='moderated by'),
        ),
        migrations.AddField(
            model_name='score',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='moderation status'),
        ),
    ]
