# Generated by Django 6.0.7 on 2026-07-15 23:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_score_moderated_at_score_moderated_by_and_more'),
        ('core', '0003_school_logo_school_principal_name'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveSmallIntegerField(verbose_name='min score')),
                ('max_score', models.PositiveSmallIntegerField(verbose_name='max score')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('remark', models.CharField(max_length=50, verbose_name='remark')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'grade scale',
                'verbose_name_plural': 'grade scales',
                'ordering': ['-min_score'],
                'unique_together': {('school', 'label')},
            },
        ),
        migrations.CreateModel(
            name='TermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.PositiveIntegerField(default=0, verbose_name='grand total')),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='average')),
                ('overall_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='overall position')),
                ('total_subjects', models.PositiveSmallIntegerField(default=0, verbose_name='total subjects')),
                ('days_present', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='days present')),
                ('days_absent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='days absent')),
                ('total_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='total school days')),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='punctuality')),
                ('neatness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='neatness')),
                ('honesty', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='honesty')),
                ('attentiveness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='attentiveness')),
                ('class_teacher_remark', models.TextField(blank=True, verbose_name='class teacher remark')),
                ('principal_remark', models.TextField(blank=True, verbose_name='principal remark')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='students.student', verbose_name='student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='core.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'term result',
                'verbose_name_plural': 'term results',
                'unique_together': {('student', 'term')},
            },
        ),
    ]
