# Generated by Django 6.0.7 on 2026-08-19 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_default_grade_scales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='exam_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='exam score'),
        ),
        migrations.AlterField(
            model_name='score',
            name='test_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='test 1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='test_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='test 2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='test_3',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='test 3'),
        ),
    ]
