# Generated by Django 6.0.7 on 2026-08-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_score_exam_score_alter_score_test_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='extra_tests',
            field=models.JSONField(blank=True, default=dict, help_text='Additional test scores, e.g. {"test_4": 8, "test_5": 9}', verbose_name='extra tests'),
        ),
    ]
