# Generated by Django 6.0.7 on 2026-08-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_score_extra_tests'),
        ('core', '0008_fix_test_max_scores'),
        ('students', '0004_plan_updates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.schoolclass', verbose_name='class'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'school_class', 'code')},
        ),
    ]
