# Generated by Django 6.0.7 on 2026-08-30 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_subject_unique_together_subject_school_class_and_more'),
        ('core', '0008_fix_test_max_scores'),
        ('students', '0004_plan_updates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='students.schoolclass', verbose_name='class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'class subject',
                'verbose_name_plural': 'class subjects',
                'ordering': ['school_class__name', 'subject__name'],
                'unique_together': {('school', 'school_class', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='school_classes',
            field=models.ManyToManyField(related_name='subjects', through='academics.ClassSubject', to='students.schoolclass', verbose_name='classes'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school_class',
        ),
    ]
