# Generated by Django 6.0.7 on 2026-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_subject_unique_together_classsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='pass_mark',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Override the subject default for this class. Leave blank to use the subject default.', null=True, verbose_name='pass mark'),
        ),
    ]
