# Generated by Django 6.0.7 on 2026-09-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_classsubject_pass_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='pass_mark',
        ),
    ]
