"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
import environ
import socket

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
env.read_env(BASE_DIR / '.env')


def _get_local_ips():
    ips = set()
    hostname = socket.gethostname()
    try:
        for ip in socket.gethostbyname_ex(hostname)[2]:
            if not ip.startswith('127.') and ':' not in ip:
                ips.add(ip)
    except Exception:
        pass
    return list(ips)


_base_allowed = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])
ALLOWED_HOSTS = _base_allowed + [ip for ip in _get_local_ips() if ip not in _base_allowed]

_base_csrf = env.list('CSRF_TRUSTED_ORIGINS', default=[])
CSRF_TRUSTED_ORIGINS = _base_csrf + [f'http://{ip}' for ip in _get_local_ips() if f'http://{ip}' not in _base_csrf]

SECRET_KEY = env('SECRET_KEY', default='')
DEBUG = env.bool('DEBUG', default=False)

INSTALLED_APPS = [
    # Local apps first
    'core',
    'fees',
    'inventory',
    'accounts',
    'students',
    'academics',
    'payroll',
    'finance',
    'notifications',
    'data_import',
    'lessons',
    'school_admin',
    # Django contrib
    'django_q',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.CurrentUserMiddleware',
    'core.middleware.SchoolMiddleware',
    'accounts.middleware.PasswordChangeRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Security hardening
SECURE_PROXY_SSL_HEADER = env.tuple('SECURE_PROXY_SSL_HEADER', default=('HTTP_X_FORWARDED_PROTO', 'https'))
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)  # False for local dev
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)  # 0 for local dev
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)  # False for local dev
SESSION_COOKIE_HTTPONLY = env.bool('SESSION_COOKIE_HTTPONLY', default=True)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)  # False for local dev
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
SECURE_CONTENT_TYPE_NOSNIFF = env.bool('SECURE_CONTENT_TYPE_NOSNIFF', default=True)
SECURE_REFERRER_POLICY = env('SECURE_REFERRER_POLICY', default='same-origin')

# ─── Production guard ───────────────────────────────────────────────────────
# When DEBUG is off, refuse to boot unless the security settings that make
# HTTPS deployment safe are explicitly set. A missing var is a hard error
# with a message pointing at the fix, not a silent downgrade.
if not DEBUG:
    _required = []
    if not SECRET_KEY or SECRET_KEY.startswith('django-insecure-'):
        _required.append('SECRET_KEY — set a real random value in .env (the old insecure default is refused)')
    if not ALLOWED_HOSTS or set(ALLOWED_HOSTS) == {'localhost', '127.0.0.1'}:
        _required.append('ALLOWED_HOSTS — set your real domain(s), e.g. app.yourschool.com')
    if not env.bool('SECURE_SSL_REDIRECT', default=False):
        _required.append('SECURE_SSL_REDIRECT=True')
    if not env.int('SECURE_HSTS_SECONDS', default=0):
        _required.append('SECURE_HSTS_SECONDS — e.g. 31536000')
    if not env.bool('SESSION_COOKIE_SECURE', default=False):
        _required.append('SESSION_COOKIE_SECURE=True')
    if not env.bool('CSRF_COOKIE_SECURE', default=False):
        _required.append('CSRF_COOKIE_SECURE=True')
    if _required:
        raise ImproperlyConfigured(
            'Production boot refused — missing security settings: '
            + '; '.join(_required)
            + '. See .env.example for the full list.'
        )

ROOT_URLCONF = 'school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.sidebar_nav',
                'core.context_processors.login_school',
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'

DATABASES = {
    'default': env.db('DATABASE_URL', default='sqlite:///db.sqlite3')
}

AUTH_USER_MODEL = 'accounts.User'

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
    # Listed last so it is never used for new logins; only for bulk
    # credential generation (see school_admin/views/credentials.py), where
    # PBKDF2's deliberate slowness would make batch resets take minutes.
    'django.contrib.auth.hashers.MD5PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'school' / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/accounts/login/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ─── Django-Q2 ──────────────────────────────────────────────────────────────
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@ghss.edu.ng')

Q_CLUSTER = {
    'name': 'GHSS',
    'orm': 'default',         # Use Django ORM as broker (no Redis needed)
    'workers': 2,
    'timeout': 30,
    'retry': 60,
    'queue_limit': 50,
    'bulk': 10,
    'sync': False,             # Async by default
}

EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
BREVO_API_KEY = env('BREVO_API_KEY', default='')

PAYSTACK_SECRET_KEY = env('PAYSTACK_SECRET_KEY', default='')
PAYSTACK_PUBLIC_KEY = env('PAYSTACK_PUBLIC_KEY', default='')
PAYSTACK_BASE_URL = env('PAYSTACK_BASE_URL', default='https://api.paystack.co')
DEFAULT_CURRENCY = env('DEFAULT_CURRENCY', default='NGN')
