# Generated by Django 6.0.7 on 2026-08-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_in_app_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'notification log', 'verbose_name_plural': 'notification logs'},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='url',
            field=models.CharField(blank=True, help_text='Optional in-app target (e.g. "/school-admin/pending-transfers/")', max_length=255, verbose_name='url'),
        ),
    ]
