# Generated by Django 6.0.7 on 2026-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationlog_options_notificationlog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='dismissed',
            field=models.BooleanField(default=False, help_text='Hidden from the bell dropdown for the recipient; the record is kept unchanged.', verbose_name='dismissed'),
        ),
    ]
