# Generated by Django 6.0.7 on 2026-08-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationlog_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='action_label',
            field=models.CharField(blank=True, help_text='Short CTA (e.g. "Review") shown on the toast for action items.', max_length=50, verbose_name='action label'),
        ),
    ]
