# Generated by Django 6.0.7 on 2026-08-20 18:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_auditlog'),
        ('students', '0003_student_passport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('level_hint', models.CharField(blank=True, max_length=100, verbose_name='level / grade hint')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='fee amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'lesson class',
                'verbose_name_plural': 'lesson classes',
                'ordering': ['period', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(blank=True, max_length=200, verbose_name='external child full name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='age')),
                ('current_class_text', models.CharField(blank=True, max_length=100, verbose_name='current class / grade')),
                ('parent_name', models.CharField(max_length=200, verbose_name='parent full name')),
                ('parent_phone', models.CharField(max_length=30, verbose_name='parent phone number')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name='emergency contact')),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], default='GUARDIAN', max_length=20, verbose_name='relationship to child')),
                ('learning_goals', models.TextField(blank=True, verbose_name='learning goals / needs')),
                ('referral_notes', models.TextField(blank=True, verbose_name='referral notes')),
                ('source', models.CharField(choices=[('REFERRAL', 'Referral'), ('SOCIAL_MEDIA', 'Social Media'), ('CHURCH', 'Church / Community'), ('SCHOOL_STAFF', 'School Staff'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='how did you hear about us?')),
                ('consent_given', models.BooleanField(default=False, verbose_name='parent consent given')),
                ('consent_date', models.DateField(blank=True, null=True, verbose_name='consent date')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20, verbose_name='status')),
                ('registered_on', models.DateTimeField(auto_now_add=True, verbose_name='registered on')),
                ('lesson_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lessons.lessonclass', verbose_name='lesson class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_enrollments', to='students.student', verbose_name='linked student')),
            ],
            options={
                'verbose_name': 'lesson enrollment',
                'verbose_name_plural': 'lesson enrollments',
                'ordering': ['-registered_on'],
            },
        ),
        migrations.CreateModel(
            name='LessonPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'lesson period',
                'verbose_name_plural': 'lesson periods',
                'ordering': ['-start_date'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='lessonclass',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_classes', to='lessons.lessonperiod', verbose_name='period'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonclass',
            unique_together={('school', 'period', 'name')},
        ),
        migrations.CreateModel(
            name='LessonTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='lessons.lessonclass', verbose_name='lesson class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'lesson teacher assignment',
                'verbose_name_plural': 'lesson teacher assignments',
                'unique_together': {('school', 'lesson_class', 'teacher')},
            },
        ),
    ]
