# Generated by Django 6.0.7 on 2026-08-26 17:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('students', '0004_plan_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonenrollment',
            name='parent_phone',
        ),
        migrations.AddField(
            model_name='lessonclass',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_classes', to='students.schoolclass', verbose_name='linked school class'),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='parent_phones',
            field=models.JSONField(blank=True, default=list, help_text='List of parent/guardian contact numbers.', verbose_name='parent phone numbers'),
        ),
        migrations.AddField(
            model_name='lessonperiod',
            name='default_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default fee for classes in this period when a class-specific fee is not set.', max_digits=10, verbose_name='default fee amount'),
        ),
        migrations.AlterField(
            model_name='lessonclass',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit the period default fee.', max_digits=10, null=True, verbose_name='fee amount'),
        ),
    ]
